# Generated by Django 4.1.7 on 2023-04-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='project_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
