# Generated by Django 4.1.7 on 2023-04-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_members',
            field=models.IntegerField(default=5),
        ),
    ]
